import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = "a2ef1f1f4e3c47c2b658705e77545db9c3c6ecf827449d86e5eae2c2b7d82a13"
REFRESH_SECRET_KEY = "b3fg2g2g5f4d58d3c769816f88656ec0d4d7fdf938550e97f6fbf3d3c8e93b24"
ALGORITHM = "HS256"

# Token expiry settings (loaded from .env)
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRY_MINUTES", 30))
REFRESH_TOKEN_EXPIRE_HOURS = int(os.getenv("REFRESH_TOKEN_EXPIRY_HOURS", 24))
SESSION_INACTIVITY_TIMEOUT_MINUTES = int(os.getenv("SESSION_INACTIVITY_TIMEOUT_MINUTES", 30))

# SECRET_KEY = os.getenv("SECRET_KEY")
# ALGORITHM = os.getenv("ALGORITHM")
# ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
URL_DATABASE = os.getenv("URL_DATABASE")
BASE_DIR = os.getenv("BASE_DIR")
BASE_URL_SUBCLASSIFICATION = os.getenv("BASE_URL_SUBCLASSIFICATION")
BASE_URL_DETECTION = os.getenv("BASE_URL_DETECTION")
